#!/usr/bin/env python3
"""
Mass curriculum translation script: Creates Thai-translated JSON files
from English curriculum JSON files. Preserves all code snippets,
technical terms, and JSON structure.
"""
import json
import os
import sys

CONTENT_DIR = os.path.join(os.path.dirname(__file__), '..', 'node', 'content')

# Thai section/key translations
TRANSLATIONS = {
    "Getting Started": "เริ่มต้นใช้งาน",
    "What is C++": "C++ คืออะไร",
    "C++ Versions": "เวอร์ชันของ C++",
    "Compilers & Build": "คอมไพเลอร์และการ Build",
    "Project Structure": "โครงสร้างโปรเจกต์",
    "Namespaces": "เนมสเปซ (Namespace)",
    "Basic Syntax": "ไวยากรณ์พื้นฐาน",
    "Variables & Types": "ตัวแปรและชนิดข้อมูล",
    "Fundamental Types": "ชนิดข้อมูลพื้นฐาน",
    "auto & decltype": "auto และ decltype",
    "Type Deduction Rules": "กฎการ Deduce ชนิด",
    "nullptr & Fixed-Width Types": "nullptr และชนิดแบบ Fixed-Width",
    "const & constexpr": "const และ constexpr",
    "Operators": "โอเปอเรเตอร์",
    "Arithmetic & Logical": "เลขคณิตและตรรกะ",
    "Bitwise & Shift": "บิตและการเลื่อน",
    "Overloaded Operators Basics": "พื้นฐานโอเปอเรเตอร์โอเวอร์โหลด",
    "User-Defined Literals": "Literal ที่ผู้ใช้กำหนด",
    "Control Flow": "การควบคุมการทำงาน",
    "if / else": "if / else",
    "Switch": "Switch",
    "Loops": "ลูป",
    "Range-Based For": "Range-Based For",
    "if constexpr": "if constexpr",
    "Structured Bindings": "Structured Bindings",
    "Init-Statements": "Init-Statements",
    "Functions": "ฟังก์ชัน",
    "Declaration & Definition": "การประกาศและนิยาม",
    "Overloading & Default Args": "Overloading และอาร์กิวเมนต์เริ่มต้น",
    "Lambda Expressions": "Lambda Expressions",
    "Trailing Return Type": "Trailing Return Type",
    "noexcept": "noexcept",
    "consteval / constinit": "consteval / constinit",
    "Function Try Blocks": "Function Try Blocks",
    "Strings": "สตริง (String)",
    "std::string": "std::string",
    "String Views": "String Views",
    "Raw String Literals": "Raw String Literals",
    "String Conversion": "การแปลงสตริง",
    "UTF-8 Support": "การรองรับ UTF-8",
    "Object-Oriented Programming": "การเขียนโปรแกรมเชิงอ็อบเจกต์ (OOP)",
    "Classes & Objects": "คลาสและอ็อบเจกต์",
    "Inheritance & Polymorphism": "Inheritance และ Polymorphism",
    "Virtual Destructors": "Virtual Destructors",
    "Pure Virtual & Abstract Classes": "Pure Virtual และ Abstract Classes",
    "Virtual Inheritance": "Virtual Inheritance",
    "Copy & Swap Idiom": "Copy & Swap Idiom",
    "Rule of Five": "Rule of Five",
    "Move Semantics": "Move Semantics",
    "RAII": "RAII",
    "STL Containers": "STL Containers",
    "std::vector": "std::vector",
    "std::map & std::set": "std::map และ std::set",
    "std::unordered_map / set": "std::unordered_map / set",
    "std::deque": "std::deque",
    "std::list & forward_list": "std::list และ forward_list",
    "Container Adaptors": "Container Adaptors",
    "std::array": "std::array",
    "STL Algorithms": "STL Algorithms",
    "sort, find, transform": "sort, find, transform",
    "lower_bound & binary_search": "lower_bound และ binary_search",
    "partial_sort & nth_element": "partial_sort และ nth_element",
    "accumulate & iota": "accumulate และ iota",
    "count_if & for_each": "count_if และ for_each",
    "Templates": "เทมเพลต (Template)",
    "Function & Class Templates": "Function และ Class Templates",
    "Template Specialization": "Template Specialization",
    "Template Template Parameters": "Template Template Parameters",
    "Variadic Templates": "Variadic Templates",
    "Fold Expressions": "Fold Expressions",
    "SFINAE & enable_if": "SFINAE และ enable_if",
    "C++20 Features": "ฟีเจอร์ C++20",
    "Concepts": "Concepts",
    "Ranges Library": "Ranges Library",
    "Coroutines": "Coroutines",
    "Modules": "Modules",
    "Spaceship Operator <=>": "Spaceship Operator <=>",
    "Views & Lazy Evaluation": "Views และ Lazy Evaluation",
    "C++23 Features": "ฟีเจอร์ C++23",
    "std::expected": "std::expected",
    "Deducing This": "Deducing This",
    "flat_map & flat_set": "flat_map และ flat_set",
    "mdspan": "mdspan",
    "Smart Pointers": "สมาร์ทพอยน์เตอร์ (Smart Pointer)",
    "std::unique_ptr": "std::unique_ptr",
    "std::shared_ptr": "std::shared_ptr",
    "std::weak_ptr": "std::weak_ptr",
    "enable_shared_from_this": "enable_shared_from_this",
    "Custom Deleters": "Custom Deleters",
    "Concurrency": "Concurrency",
    "std::thread": "std::thread",
    "Mutex & Locks": "Mutex และ Locks",
    "Async & Futures": "Async และ Futures",
    "std::jthread": "std::jthread",
    "std::latch & std::barrier": "std::latch และ std::barrier",
    "std::counting_semaphore": "std::counting_semaphore",
    "File I/O": "File I/O",
    "std::fstream Basics": "พื้นฐาน std::fstream",
    "std::filesystem": "std::filesystem",
    "std::stringstream": "std::stringstream",
    "Binary I/O": "Binary I/O",
    "Error Handling": "การจัดการข้อผิดพลาด",
    "Exceptions": "Exceptions",
    "noexcept Specifier": "noexcept Specifier",
    "std::exception Hierarchy": "ลำดับชั้น std::exception",
    "Error Codes & std::error_code": "Error Codes และ std::error_code",
    "Build Systems": "ระบบ Build",
    "CMake Deep": "CMake เจาะลึก",
    "vcpkg": "vcpkg",
    "Conan": "Conan",
    "Build Tools Overview": "ภาพรวมเครื่องมือ Build",
    "Frameworks": "เฟรมเวิร์ก",
    "Qt Framework": "Qt Framework",
    "Boost Libraries": "Boost Libraries",
    "Unreal Engine C++": "Unreal Engine C++",
    "Google Test & Benchmark": "Google Test และ Benchmark",
    "Utilities & Type Support": "Utilities และ Type Support",
    "std::optional (C++17)": "std::optional (C++17)",
    "std::variant (C++17)": "std::variant (C++17)",
    "std::any (C++17)": "std::any (C++17)",
    "Type Traits & Metaprogramming": "Type Traits และ Metaprogramming",
    "Modern C++ Practice": "แนวปฏิบัติ C++ สมัยใหม่",
    "Inline Variables (C++17)": "Inline Variables (C++17)",
    "[[nodiscard]] & [[maybe_unused]]": "[[nodiscard]] และ [[maybe_unused]]",
    "std::clamp / std::gcd / std::lcm (C++17)": "std::clamp / std::gcd / std::lcm (C++17)",
    "Parallel STL Algorithms (C++17)": "Parallel STL Algorithms (C++17)",
    "Code Organization (PIMPL Idiom)": "การจัดระเบียบโค้ด (PIMPL Idiom)",
    "Design Patterns: Strategy & Observer": "Design Patterns: Strategy และ Observer",
    "Testing with Catch2 & GTest": "การทดสอบด้วย Catch2 และ GTest",
    "Performance Optimization": "การเพิ่มประสิทธิภาพ",
    "Pointers & Memory": "พอยน์เตอร์และหน่วยความจำ",
    "References": "References",
    "Raw Pointers": "Raw Pointers",
    "new & delete": "new และ delete",
    "Memory Leakage": "Memory Leakage",
    "Memory Model": "Memory Model",
    "Object Lifetime": "Object Lifetime",
    "Type Casting": "การแปลงชนิด (Type Casting)",
    "static_cast": "static_cast",
    "dynamic_cast": "dynamic_cast",
    "const_cast": "const_cast",
    "reinterpret_cast": "reinterpret_cast",
    "RTTI & typeid": "RTTI และ typeid",
    "Language Internals": "ภายในภาษา",
    "Undefined Behavior": "Undefined Behavior",
    "ADL": "ADL",
    "Name Mangling": "Name Mangling",
    "Macros": "Macros",
    "Forward Declaration": "Forward Declaration",
    "Scope & Storage Duration": "Scope และ Storage Duration",
    "Inheritance & Advanced OOP": "Inheritance และ OOP ขั้นสูง",
    "Multiple Inheritance": "Multiple Inheritance",
    "Diamond Inheritance": "Diamond Inheritance",
    "Virtual Tables": "Virtual Tables",
    "Dynamic Polymorphism": "Dynamic Polymorphism",
    "Debugging": "การดีบัก (Debugging)",
    "GDB Basics": "พื้นฐาน GDB",
    "Debugging Symbols": "Debugging Symbols",
    "Sanitizers": "Sanitizers",
    "std::latch, std::barrier & std::semaphore": "std::latch, std::barrier และ std::semaphore",
    "noexcept & noexcept Specifier Deep": "noexcept และ noexcept Specifier เจาะลึก",
    "Pointers": "พอยน์เตอร์",
    "Memory Management": "การจัดการหน่วยความจำ",
    "Functions & Methods": "ฟังก์ชันและเมธอด",
    "What is C#": "C# คืออะไร",
    "What is .NET?": ".NET คืออะไร",
    "IDE & Editor Choices": "การเลือก IDE และ Editor",
    "Top-Level Statements": "Top-Level Statements",
    "File-Scoped Namespaces": "File-Scoped Namespaces",
    "Project Types & Templates": "ประเภทโปรเจกต์และเทมเพลต",
    "Project Structure & SDKs": "โครงสร้างโปรเจกต์และ SDK",
    "Primitive Types": "ชนิดข้อมูลพื้นฐาน",
    "var & Implicit Typing": "var และการกำหนดชนิดแบบ Implicit",
    "object & dynamic": "object และ dynamic",
    "Nullable Value Types": "Nullable Value Types",
    "Nullable Reference Types": "Nullable Reference Types",
    "Null-Forgiving Operator": "Null-Forgiving Operator",
    "Constants & Readonly": "Constants และ Readonly",
    "Tuple Types": "Tuple Types",
    "Comparison & Equality": "การเปรียบเทียบและความเท่ากัน",
    "Logical & Bitwise": "ตรรกะและบิต",
    "Null-Conditional Operator": "Null-Conditional Operator",
    "Null-Coalescing Operators": "Null-Coalescing Operators",
    "Switch Expressions": "Switch Expressions",
    "Conditional Operator": "Conditional Operator",
    "if / else if / else": "if / else if / else",
    "Switch Statement": "Switch Statement",
    "Pattern Matching": "Pattern Matching",
    "for Loop": "for Loop",
    "foreach Loop": "foreach Loop",
    "while & do-while": "while และ do-while",
    "break, continue, goto": "break, continue, goto",
    "using Declaration": "using Declaration",
    "Params Keyword": "Params Keyword",
    "Optional & Named Parameters": "Optional และ Named Parameters",
    "Expression-Bodied Members": "Expression-Bodied Members",
    "Local Functions": "Local Functions",
    "Return Values & Multiple Returns": "Return Values และ Multiple Returns",
    "Delegates & Lambda Expressions": "Delegates และ Lambda Expressions",
    "Fields & Properties": "Fields และ Properties",
    "Init Setters & Required Members": "Init Setters และ Required Members",
    "Primary Constructors": "Primary Constructors",
    "Record Types": "Record Types",
    "Inheritance": "Inheritance",
    "Polymorphism": "Polymorphism",
    "Abstract Classes & Sealed": "Abstract Classes และ Sealed",
    "Static Members & Classes": "Static Members และ Classes",
    "Object Initializers": "Object Initializers",
    "Default Interface Methods": "Default Interface Methods",
    "Generic Constraints": "Generic Constraints",
    "Covariance & Contravariance": "Covariance และ Contravariance",
    "Generic Methods": "Generic Methods",
    "IDisposable & IAsyncDisposable": "IDisposable และ IAsyncDisposable",
    "LINQ Basics": "พื้นฐาน LINQ",
    "LINQ Methods Deep": "LINQ Methods เจาะลึก",
    "LINQ GroupBy & Joins": "LINQ GroupBy และ Joins",
    "Concurrent Collections": "Concurrent Collections",
    "PLINQ (Parallel LINQ)": "PLINQ (Parallel LINQ)",
    "Exception Filters (when)": "Exception Filters (when)",
    "Custom Exceptions": "Custom Exceptions",
    "Guard Clauses & Argument Validation": "Guard Clauses และ Argument Validation",
    "Throw Helpers": "Throw Helpers",
    "Result Pattern (Functional Error Handling)": "Result Pattern (Functional Error Handling)",
    "async / await Basics": "พื้นฐาน async / await",
    "Task & Task<T>": "Task และ Task<T>",
    "Cancellation": "Cancellation",
    "ValueTask & ValueTask<T>": "ValueTask และ ValueTask<T>",
    "Async Streams (IAsyncEnumerable)": "Async Streams (IAsyncEnumerable)",
    "Channel<T>": "Channel<T>",
    "Task Parallel Library (Dataflow)": "Task Parallel Library (Dataflow)",
    "Thread Synchronization": "Thread Synchronization",
    "Parallel.For / Parallel.ForEach": "Parallel.For / Parallel.ForEach",
    "File & Directory Operations": "File และ Directory Operations",
    "StreamReader / StreamWriter": "StreamReader / StreamWriter",
    "System.Text.Json": "System.Text.Json",
    "System.Text.Json Source Generators": "System.Text.Json Source Generators",
    "XML Serialization": "XML Serialization",
    "Binary Serialization (obsolete)": "Binary Serialization (เลิกใช้)",
    "Protocol Buffers (Protobuf)": "Protocol Buffers (Protobuf)",
    "Span<T> & ReadOnlySpan<T>": "Span<T> และ ReadOnlySpan<T>",
    "Memory<T> & ReadOnlyMemory<T>": "Memory<T> และ ReadOnlyMemory<T>",
    "ref struct & readonly ref struct": "ref struct และ readonly ref struct",
    "stackalloc": "stackalloc",
    "Unsafe Code & Pointers": "Unsafe Code และ Pointers",
    "Ref Returns & Ref Locals": "Ref Returns และ Ref Locals",
    "Memory Pool & ArrayPool": "Memory Pool และ ArrayPool",
    "WeakReference & Conditional Weak Tables": "WeakReference และ Conditional Weak Tables",
    "P/Invoke (Platform Invoke)": "P/Invoke (Platform Invoke)",
    "COM Interop": "COM Interop",
    "Fixed Size Buffers": "Fixed Size Buffers",
    "Marshal Class": "Marshal Class",
    "WinRT Interop & COM": "WinRT Interop และ COM",
    "xUnit.net Basics": "พื้นฐาน xUnit.net",
    "NUnit Basics": "พื้นฐาน NUnit",
    "Moq (Mocking)": "Moq (Mocking)",
    "FluentAssertions": "FluentAssertions",
    "TDD with C#": "TDD ด้วย C#",
    "xUnit & Fluent Assertions": "xUnit และ Fluent Assertions",
    "NuGet Package Manager": "NuGet Package Manager",
    "ASP.NET Core Minimal API": "ASP.NET Core Minimal API",
}

def translate_key(key):
    """Translate a section/topic key to Thai, keeping original if no translation."""
    return TRANSLATIONS.get(key, key)

def translate_dict(data):
    """Recursively translate dictionary keys."""
    if isinstance(data, dict):
        return {translate_key(k) if not k.startswith(' ') else k: translate_dict(v) for k, v in data.items()}
    return data

def translate_file(src_file):
    """Translate a single curriculum file from English to Thai."""
    src_path = os.path.join(CONTENT_DIR, src_file)
    # Determine output name: replace root name with _th suffix
    base, ext = os.path.splitext(src_file)
    dst_file = f"{base}_th.json"
    dst_path = os.path.join(CONTENT_DIR, dst_file)

    # Skip if Thai file already exists
    if os.path.exists(dst_path):
        print(f"SKIP {dst_file} already exists")
        return
    
    with open(src_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Translate top-level keys (sections)
    translated = {}
    for section_key, section_value in data.items():
        thai_section = translate_key(section_key)
        if isinstance(section_value, dict):
            translated[thai_section] = translate_dict(section_value)
        else:
            translated[thai_section] = section_value

    with open(dst_path, 'w', encoding='utf-8') as f:
        json.dump(translated, f, ensure_ascii=False, indent=2)

    print(f"OK Created {dst_file} ({os.path.getsize(dst_path)} bytes)")

def main():
    files = sys.argv[1:] if len(sys.argv) > 1 else os.listdir(CONTENT_DIR)
    for fname in files:
        if fname.endswith('.json') and not fname.endswith('_th.json') and fname != 'app-data.json' and fname != 'curriculum.json':
            translate_file(fname)

if __name__ == '__main__':
    main()
